spring:
 cloud:
  gateway:
   routes:
    - id: book-service 
      uri: http://localhost:8080
      predicates: 
       - Path=/api/book/**
      filters:
       - AddRequestHeader=X-Request-Custom, red
       - AddResponseHeader=X-Response-Custom, red